# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Channel

# Model Form Field configuration
form: @/plugins/rainlab/forum/models/channel/fields.yaml

# Model Class name
modelClass: RainLab\Forum\Models\Channel

# Default redirect location
defaultRedirect: rainlab/forum/channels

# Create page
create:
    title: Create Channels
    redirect: rainlab/forum/channels/update/:id
    redirectClose: rainlab/forum/channels

# Update page
update:
    title: Edit Channels
    redirect: rainlab/forum/channels
    redirectClose: rainlab/forum/channels

# Preview page
preview:
    title: Preview Channels